PyKrx

# 1. 환경

In [20]:
!pip install pykrx

In [21]:
from pykrx import stock #pykrx는 유가 증권시장 주식정보 스크래핑

# 2.API

# 2.1 stock 모듈
# 2.1.1 MarketData API
코스피 종목의 주가 관련 정보를 얻는 API

# 2.1.1.1 Ticker 조회
get_market_ticker_list 메서드는 지정한 일자(YYMMDD)의 코스피 시장에 상장된 ticker를 리스트로 반환

In [6]:
tickers = stock.get_market_ticker_list("20210222")
print(tickers)

['095570', '006840', '027410', '282330', '138930', '001460', '001465', '001040', '079160', '00104K', '000120', '011150', '011155', '001045', '097950', '097955', '000590', '012030', '016610', '005830', '000990', '000995', '139130', '001530', '000210', '000215', '375500', '37550K', '004840', '155660', '069730', '017940', '365550', '007700', '114090', '078930', '006360', '001250', '007070', '078935', '012630', '039570', '089470', '294870', '011200', '082740', '003560', '175330', '234080', '001060', '001067', '001065', '096760', '105560', '002380', '009070', '009440', '119650', '092220', '016380', '016385', '001390', '001940', '025000', '092230', '000040', '044450', '030200', '033780', '030210', '058850', '058860', '093050', '003550', '034220', '001120', '051900', '051905', '003555', '032640', '011070', '066570', '066575', '108670', '108675', '037560', '051910', '051915', '079550', '006260', '010120', '000680', '229640', '023150', '035420', '181710', '005940', '005945', '338100', '034310',

날짜를 지정하지 않으면 내부적으로 최근 영업일을 계산해서 ticker 반환. 
최근 영업일을 조회하는 시간이 추가로 소모되지만 사용상의 차이점은 없습니다.

In [10]:
tickers = stock.get_market_ticker_list()
print(tickers)

['095570', '006840', '027410', '282330', '138930', '001460', '001465', '001040', '079160', '00104K', '000120', '011150', '011155', '001045', '097950', '097955', '000590', '012030', '016610', '005830', '000990', '000995', '139130', '001530', '000210', '001880', '000215', '375500', '37550K', '004840', '155660', '069730', '017940', '365550', '007700', '114090', '078930', '006360', '001250', '007070', '078935', '012630', '039570', '089470', '294870', '011200', '082740', '003560', '175330', '234080', '001060', '001067', '001065', '096760', '105560', '002380', '009070', '009440', '119650', '092220', '016380', '016385', '001390', '001940', '025000', '092230', '000040', '044450', '030200', '033780', '030210', '058850', '058860', '093050', '003550', '034220', '001120', '051900', '051905', '003555', '032640', '011070', '066570', '066575', '108670', '108675', '037560', '051910', '051915', '079550', '006260', '010120', '000680', '229640', '023150', '035420', '181710', '005940', '005945', '338100',

market 옵션을 추가하면 조회 시장을 지정할 수 있습니다.
KOSPI, KOSDAQ, KONEX 시장을 지정할 수 있으며, ALL은 모든 시장에서 티커를 조회합니다. 입력하지 않을 경우 KOSPI 시장을 조회합니다.

In [11]:
tickers = stock.get_market_ticker_list("20210222", market="KOSDAQ")
print(tickers)

['060310', '054620', '265520', '211270', '035760', '051500', '058820', '023460', '056000', '065770', '083660', '367340', '068790', '241520', '245620', '037370', '079190', '130500', '900290', '083450', '028150', '045890', '078150', '036640', '335870', '351340', '351320', '095340', '099520', '950170', '067290', '035900', '024840', '024120', '021320', '036670', '044180', '151860', '046440', '035600', '060720', '122450', '052900', '058400', '114450', '036030', '060370', '065150', '219550', '160550', '053290', '104200', '060250', '030190', '078590', '178920', '024940', '218410', '091340', '019550', '950110', '046140', '036120', '099220', '036540', '255220', '040610', '049470', '184230', '016250', '307070', '337450', '340350', '036490', '048550', '063440', '950180', '289080', '089230', '161570', '032540', '048770', '246690', '317240', '038340', '073570', '052300', '057030', '040300', '051390', '052220', '079940', '078890', '192410', '217730', '114190', '094480', '063080', '044480', '039240',

get_market_ticker_name 함수에 티커를 입력하면 종목이름을 반환

In [12]:
for ticker in stock.get_market_ticker_list():
        종목 = stock.get_market_ticker_name(ticker)
        print(종목)

AJ네트웍스
AK홀딩스
BGF
BGF리테일
BNK금융지주
BYC
BYC우
CJ
CJ CGV
CJ4우(전환)
CJ대한통운
CJ씨푸드
CJ씨푸드1우
CJ우
CJ제일제당
CJ제일제당 우
CS홀딩스
DB
DB금융투자
DB손해보험
DB하이텍
DB하이텍1우
DGB금융지주
DI동일
DL
DL건설
DL우
DL이앤씨
DL이앤씨우
DRB동일
DSR
DSR제강
E1
ESR켄달스퀘어리츠
F&F
GKL
GS
GS건설
GS글로벌
GS리테일
GS우
HDC
HDC아이콘트롤스
HDC현대EP
HDC현대산업개발
HMM
HSD엔진
IHQ
JB금융지주
JW생명과학
JW중외제약
JW중외제약2우B
JW중외제약우
JW홀딩스
KB금융
KCC
KCTC
KC그린홀딩스
KC코트렐
KEC
KG동부제철
KG동부제철우
KG케미칼
KISCO홀딩스
KPX케미칼
KPX홀딩스
KR모터스
KSS해운
KT
KT&G
KTB투자증권
KTcs
KTis
LF
LG
LG디스플레이
LG상사
LG생활건강
LG생활건강우
LG우
LG유플러스
LG이노텍
LG전자
LG전자우
LG하우시스
LG하우시스우
LG헬로비전
LG화학
LG화학우
LIG넥스원
LS
LS ELECTRIC
LS네트웍스
LS전선아시아
MH에탄올
NAVER
NHN
NH투자증권
NH투자증권우
NH프라임리츠
NICE
NI스틸
NPC
NPC우
OCI
POSCO
S-Oil
S-Oil우
SBS
SBS미디어홀딩스
SGC에너지
SG세계물산
SG충방
SH에너지화학
SIMPAC
SJM
SJM홀딩스
SK
SKC
SK가스
SK네트웍스
SK네트웍스우
SK디스커버리
SK디스커버리우
SK디앤디
SK렌터카
SK바이오사이언스
SK바이오팜
SK우
SK이노베이션
SK이노베이션우
SK증권
SK증권우
SK케미칼
SK케미칼우
SK텔레콤
SK하이닉스
SNT모티브
SNT에너지
SNT중공업
SNT홀딩스
SPC삼립
STX
STX엔진
STX중공업
TBH글로벌
TCC스틸
WISCOM
YG PLUS
가온전선
강남제비스코
강원랜드
갤럭시아에스엠
경농
경동나비엔
경동도시가스
경동인베스트
경방
경보제약
경인양행
경인전자
계룡건설
계양전기

# 2.1.1.2 일자별 OHLCV 조회
get_market_ohlcv_by_date 함수는 시작일/종료일/티커 세 개의 파라미터를 입력받아 OHLCV를 일자별로 정렬하여 DataFrame으로 반환

In [13]:
df = stock.get_market_ohlcv_by_date("20150720", "20150810", "005930")
print(df.head(3))

               시가     고가     저가     종가     거래량
날짜                                            
2015-07-20  25820  26080  25460  25500  128928
2015-07-21  25500  25540  24940  25260  194055
2015-07-22  24880  25200  24700  25060  268323


과거 일자의 OHLCV가 위쪽에 위치하는 것을 확인할 수 있습니다.

get_market_ohlcv_by_date() 함수에 frequency 파라미터(d/m/y)를 추가할 수 있습니다. d는 일자, m은 월, y는 연도를 의미합니다. 다음은 20210102부터 20210401까지의 삼성전자 월별 OHLCV 데이터를 출력합니다.

In [14]:
df = stock.get_market_ohlcv_by_date("20210102", "20210401", "005930", "m")
print(df.head(3))

               시가     고가     저가     종가        거래량
날짜                                               
2021-01-31  81000  96800  80200  82000  765471247
2021-02-28  81700  86400  81000  82500  432953240
2021-03-31  85100  85300  80600  81400  387612356


# 2.1.1.3 전체 종목 시세 조회
get_market_ohlcv_by_ticker 함수는 입력된 일자의 코스피 전종목 시세를 DataFrame으로 반환

In [23]:
df = stock.get_market_ohlcv_by_ticker("20210122")
print(df.head(3))

           시가     고가     저가     종가      거래량         거래대금    등락률
티커                                                             
095570   4190   4245   4160   4210   216835    910274405   0.84
006840  25750  29550  25600  29100   727088  20462325950  12.57
027410   5020   5250   4955   5220  1547629   7990770515   4.19


두 번째 파라미터에 특정 시장을 지정해서 종목 시세를 조회할 수 있습니다.

● 코스피(KOSPI)/코스닥(KOSDAQ)/코넥스(KONEX) 시장을 지원합니다.
● ALL을 입력하면 전체 시장을 조회합니다.
● 값을 입력하지 않는다면 코스피 시장을 조회합니다.

In [24]:
df = stock.get_market_ohlcv_by_ticker("20210131", market="KOSPI")
df = stock.get_market_ohlcv_by_ticker("20210131", market="KOSDAQ")
df = stock.get_market_ohlcv_by_ticker("20210131", market="KONEX")

# 2.1.1.4 모든 종목 가격 변동 조회
get_market_price_change_by_ticker 함수는 입력된 기간 동안의 가격 가격 변동 정보를 반환합니다. 다음 코드는 20180301-20180320 동안의 가격 변동폭을 조회합니다. 

In [26]:
df = stock.get_market_price_change_by_ticker("20210301", "20210320")
print(df.head(2))

           종목명     시가     종가   변동폭     등락률      거래량         거래대금
티커                                                              
095570  AJ네트웍스   3885   4440   555  1429.0  1348783   5587542590
006840   AK홀딩스  31250  30100 -1150  -368.0  1089833  32720148700


시작일의 시가 혹은 전일 종가를 가격 변동 데이터의 시가로 사용할 수 있는데, KRX 웹서버는 전일 종가를 시가로 반환합니다. 즉 20210301 전일 종가를 시가, 20210320을 종가로 사용합니다.

In [30]:
df = stock.get_market_ohlcv_by_date("20210225", "20210320", "000020")
print(df.head())

               시가     고가     저가     종가     거래량
날짜                                            
2021-02-25  13900  14450  13800  14450  244951
2021-02-26  13950  14500  13800  14500  242941
2021-03-02  14750  14750  14100  14300  199410
2021-03-03  14150  14500  14100  14300  127587
2021-03-04  14200  14250  13600  13750  225778


위의 동화약품(000020)의 경우를 살펴보면 2021/03/02의 전일 영업일 2021/02/26의 종가를 시가로 사용한 것을 알 수 있습니다.

# 2.1.1.5 종목별 DIV/BPS/PER/EPS 조회
get_market_fundamental_by_ticker 함수는 코스피 시장의 DIV/BPS/PER/EPS/PBR를 조회합니다.

In [37]:
df = stock.get_market_fundamental_by_ticker("20210108")
print(df.head(2))

          BPS        PER       PBR   EPS       DIV  DPS
티커                                                     
095570   6802   4.621094  0.669922   982  6.609375  300
006840  62448  11.687500  0.409912  2168  2.960938  750


두 번재 market 파라미터를 사용하면 특정 시장을 조회할 수 있습니다.

KOSPI / KOSDAQ / KONEX / ALL 을 사용할 수 있습니다.

In [39]:
df = stock.get_market_fundamental_by_ticker("20210104", market="KOSDAQ")
print(df.head(2))

          BPS  PER       PBR  EPS  DIV  DPS
티커                                         
060310    745  0.0  3.029297    0  0.0    0
054620  10530  0.0  0.759766    0  0.0    0


# 2.1.1.6 일자별 DIV/BPS/PER/EPS 조회
get_market_fundamental_by_date 함수는 특정 종목에 대해 입력된 기간의 DIV/BPS/PER/EPS/PBR를 조회합니다.

In [40]:
df = stock.get_market_fundamental_by_date("20210104", "20210108", "005930")
print(df.head(2))

              BPS    PER   PBR   EPS   DIV   DPS
날짜                                              
2021-01-04  37528  26.22  2.21  3166  1.71  1416
2021-01-05  37528  26.50  2.24  3166  1.69  1416


get_market_fundamental_by_date() 함수에 frequency 파라미터(d/m/y)를 추가할 수 있습니다. d는 일자, m은 월, y는 연도를 의미합니다.

In [42]:
df = stock.get_market_fundamental_by_date("20210110", "20210410", "005930", freq="m")
print(df.head(2))

              BPS    PER   PBR   EPS   DIV   DPS
날짜                                              
2021-01-31  37528  28.74  2.42  3166  1.56  1416
2021-02-28  37528  26.22  2.21  3166  1.71  1416


다음은 20210110부터 20210410까지의 삼성전자 월별 DIV/BPS/PER/EPS를 출력합니다. 이때 해당 월의 종가를 기준으로 값이 출력됩니다.

# 2.1.1.7 일자별 거래실적 추이 (거래대금)

지정된 기간 동안의 일자별로 정렬된 (순매수) 거래량을 얻어옵니다. 당일자 최종 매매내역은 오후 6시 이후에 제공됩니다. 다음은 삼성전자 (005930)의 2021-01-15부터 2021-01-22까지의 거래대금을 얻어옵니다.

In [43]:
df = stock.get_market_trading_value_by_date("20210115", "20210122", "005930")
print(df.head())

                    기관합계         기타법인            개인         외국인합계  전체
날짜                                                                   
2021-01-15 -440769209300  25442287800  661609085600 -246282164100   0
2021-01-18   42323535000  22682344800   14829121700  -79835001500   0
2021-01-19   95523053500  -3250422500 -173484213300   81211582300   0
2021-01-20 -364476214000  22980632900  430115581000  -88619999900   0
2021-01-21  -60637506300 -27880854000  250285510000 -161767149700   0


매수 혹은 매도 금액을 조회하고 싶다면 on 파라미터에 입력할 수 있습니다. 입력하지 않는다면 순매수 금액이 조회됩니다.

In [44]:
df = stock.get_market_trading_value_by_date("20210115", "20210122", "005930", on='매도')
print(df.head())

                     기관합계         기타법인             개인         외국인합계  \
날짜                                                                    
2021-01-15  1505250243300  19525756900   925426195700  525029741764   
2021-01-18  1353223733500  22132983500  1883422627200  456996648400   
2021-01-19  1205081446400  28155090000  1800734616800  407371601300   
2021-01-20  1147190346800  10015618200   643413644500  405119540200   
2021-01-21   878411497500  41184362100   851899126900  439714802000   

                       전체  
날짜                         
2021-01-15  2975231937664  
2021-01-18  3715775992600  
2021-01-19  3441342754500  
2021-01-20  2205739149700  
2021-01-21  2211209788500  


세 번째 파라미터에 KOSPI, KOSDAQ, KONEX를 사용하면 각 시장의 거래대금을 조회합니다. ALL을 입력하면 세 개의 시장을 합친 통합 거래대금을 조회합니다.

In [45]:
df = stock.get_market_trading_value_by_date("20210115", "20210122", "KOSPI")
print(df.head())

                     기관합계         기타법인             개인         외국인합계  전체
날짜                                                                     
2021-01-15 -1414745885546  54444293672  2113924037705 -753622445831   0
2021-01-18  -278880716957 -26004926379   514299140387 -209413497051   0
2021-01-19   593956459208  21472281148 -1025418915468  409990175112   0
2021-01-20 -1234485992694  34510184945  1436793223994 -236817416245   0
2021-01-21  -292666343147 -13168420832   -62476631241  368311395220   0


시장의 거래대금을 조회할 때는 ETF, ETN ELW의 포함 여부를 지정할 수 있습니다. 만약 값을 지정하지 않는다면 해당 데이터를 제외한 값을을 반환합니다. 옵션은 KOSPI, KOSDAQ, KONEX 조회할 때만 유효합니다.

In [46]:
df = stock.get_market_trading_value_by_date("20210115", "20210122", "KOSPI", etf=True, etn=True, elw=True)
print(df.head())

                     기관합계         기타법인             개인         외국인합계  전체
날짜                                                                     
2021-01-15 -1536570309441  63110174617  2251672617980 -778212483156   0
2021-01-18  -601428111357 -27000808439   494341183227  134087736569   0
2021-01-19   544654406338  21787409868  -968965427363  402523611157   0
2021-01-20 -1227642472619  32139813590  1444113501769 -248610842740   0
2021-01-21  -284899892322 -19072459127   -61503500921  365475852370   0


detail 옵션을 추가하면 상세한 정보를 얻을 수 있습니다. 옵션은 KOSPI, KOSDAQ, KONEX 조회할 때만 유효합니다.

In [47]:
df = stock.get_market_trading_value_by_date("20210115", "20210122", "KOSPI", etf=True, etn=True, elw=True, detail=True)
print(df.head())

                     금융투자            보험            투신           사모  \
날짜                                                                   
2021-01-15  -991569370471 -101879326615  -73654664921 -47097103944   
2021-01-18  -234901037556  -72240710086  101791257920 -22451555756   
2021-01-19  1095649201830  -16407303019 -132856710155  12116061569   
2021-01-20  -642974676550  -63074125224  -93392192931  -2355882539   
2021-01-21   354360314201 -107524405663  -12601355617  21898580074   

                      은행          기타금융           연기금         기타법인  \
날짜                                                                  
2021-01-15  202104737955   -4226413080 -520248168365  63110174617   
2021-01-18   29622542645    9331964150 -412580572674 -27000808439   
2021-01-19    1776752770   -1933723125 -413689873532  21787409868   
2021-01-20  -17889264145   -1573759250 -406382571980  32139813590   
2021-01-21 -113225122905 -158268629075 -269539273337 -19072459127   

                       개인

# 2.1.1.8 일자별 거래실적 추이 (거래량)
일자별 시장의 거래량을 조회합니다. 당일자 최종 매매내역은 오후 6시 이후에 제공됩니다. 다음은 삼성전자 (005930)의 2021-01-15부터 2021-01-22까지의 거래량을 얻어옵니다.

In [49]:
df = stock.get_market_trading_volume_by_date("20210115", "20210122", "005930")
print(df.head())

               기관합계    기타법인       개인    외국인합계  전체
날짜                                               
2021-01-15 -5006115  288832  7485785 -2768502   0
2021-01-18   505669  262604   151228  -919501   0
2021-01-19  1139258  -34023 -2044543   939308   0
2021-01-20 -4157919  262408  4917655 -1022144   0
2021-01-21  -712099 -321732  2890389 -1856558   0


매수 혹은 매도 거래량만을 조회하고 싶다면 on 파라미터에 입력할 수 있습니다. 입력하지 않는다면 순매수 수량이 조회됩니다.

In [50]:
df = stock.get_market_trading_volume_by_date("20210115", "20210122", "005930", on='매도')
print(df.head())

                기관합계    기타법인        개인    외국인합계        전체
날짜                                                       
2021-01-15  16944750  216653  10371182  5899224  33431809
2021-01-18  15709256  258096  21942253  5318346  43227951
2021-01-19  13912581  323382  20956376  4702705  39895044
2021-01-20  13121791  114341   7346474  4628521  25211127
2021-01-21  10093381  473635   9714878  5036117  25318011


세 번째 파라미터에 KOSPI, KOSDAQ, KONEX를 사용하면 각 시장의 거래량을 조회합니다. ALL을 입력하면 세 개의 시장을 합친 통합 거래량을 조회합니다.

In [51]:
df = stock.get_market_trading_volume_by_date("20210115", "20210122", "KOSPI")
print(df.head())

                기관합계     기타법인        개인     외국인합계  전체
날짜                                                   
2021-01-15 -20393142  8435634  29119751 -17162243   0
2021-01-18  -5700054 -1198498  15316328  -8417776   0
2021-01-19   7216278  -246496 -24395243  17425461   0
2021-01-20 -23038683  -793906  31606917  -7774328   0
2021-01-21 -18443990 -7082091   8365421  17160660   0


시장의 거래량을 조회할 때는 ETF, ETN ELW의 포함 여부를 지정할 수 있습니다. 만약 값을 지정하지 않는다면 해당 데이터를 제외한 값을을 반환합니다. 옵션은 KOSPI, KOSDAQ, KONEX 조회할 때만 유효합니다.

In [52]:
df = stock.get_market_trading_volume_by_date("20210115", "20210122", "KOSPI", etf=True, etn=True, elw=True)
print(df.head())

                기관합계     기타법인        개인     외국인합계  전체
날짜                                                   
2021-01-15 -26571037  8455599  37942108 -19826670   0
2021-01-18 -65039501  -757841  39922005  25875337   0
2021-01-19 -41855511  4320588  31709703   5825220   0
2021-01-20 -23038880 -2562184  38031657 -12430593   0
2021-01-21 -38539026 -8798430  38195538   9141918   0


detail 옵션을 추가하면 상세한 정보를 얻을 수 있습니다. 옵션은 KOSPI, KOSDAQ, KONEX 조회할 때만 유효합니다

In [53]:
df = stock.get_market_trading_volume_by_date("20210115", "20210122", "KOSPI", etf=True, etn=True, elw=True, detail=True)
print(df.head())

                금융투자       보험        투신       사모        은행     기타금융      연기금  \
날짜                                                                             
2021-01-15 -30909240 -1400206   2245052 -2307623  11071023   102571 -5372614   
2021-01-18 -70318619 -1883526   9224883    10962   3203493   394649 -5671343   
2021-01-19 -24047200  -161246 -11083467 -1024629    216630  -150452 -5605147   
2021-01-20 -10187734 -1024404  -3957101  -523064   -556527   163402 -6953452   
2021-01-21 -13155430 -3602153  -2107802  -742226  -3466644 -8481152 -6983619   

               기타법인        개인       외국인   기타외국인  전체  
날짜                                                   
2021-01-15  8455599  37942108 -19793169  -33501   0  
2021-01-18  -757841  39922005  25583326  292011   0  
2021-01-19  4320588  31709703   5392346  432874   0  
2021-01-20 -2562184  38031657 -12710114  279521   0  
2021-01-21 -8798430  38195538   8855139  286779   0  


# 2.1.1.9 투자자별 거래실적 추이 (거래대금)

지정된 기간 동안의 투자자별로 정렬된 (순매수) 거래대금을 얻어옵니다. 당일자 최종 매매내역은 오후 6시 이후에 제공됩니다. 다음은 삼성전자 (005930)의 2021-01-15부터 2021-01-22까지의 거래대금을 얻어옵니다.

In [54]:
df = stock.get_market_trading_value_by_investor("20210115", "20210122", "005930")
print(df.head())

                  매도             매수           순매수
투자자구분                                            
금융투자   2580964135000  2309054317700 -271909817300
보험      153322228800    44505136200 -108817092600
투신      258073006600   150715203700 -107357802900
사모       65167773900    60862926800   -4304847100
은행        3369626100     4004806100     635180000


# 2.1.1.10 투자자별 거래실적 추이 (거래량)

지정된 기간 동안의 투자자별로 정렬된 (순매수) 거래량을 얻어옵니다. 당일자 최종 매매내역은 오후 6시 이후에 제공됩니다. 다음은 삼성전자 (005930)의 2021-01-15부터 2021-01-22까지의 거래량을 얻어옵니다.

In [55]:
df = stock.get_market_trading_volume_by_investor("20210115", "20210122", "005930")
print(df.head())

             매도        매수      순매수
투자자구분                             
금융투자   29455909  26450600 -3005309
보험      1757287    509535 -1247752
투신      2950680   1721970 -1228710
사모       745727    696135   -49592
은행        38675     46394     7719


# 2.1.1.11 투자자별 순매수 상위종목
get_market_net_purchases_of_equities_by_ticker 함수는 순매수 금액 순서로 정렬된 종목 리스트를 반환합니다. 다음은 코스피 시장에서 2021-01-15 부터 2021-01-22 까지 개인의 순매수 금액이 높은 순서대로 종목을 정렬해서 반환합니다.

In [56]:
df = stock.get_market_net_purchases_of_equities_by_ticker("20210115", "20210122", "KOSPI", "개인")
print(df.head())

            종목명     매도거래량      매수거래량    순매수거래량         매도거래대금         매수거래대금  \
티커                                                                             
005930     삼성전자  79567418  102852747  23285329  6918846810800  8972911580500   
000270      기아차  44440252   49880626   5440374  3861283906400  4377698855000   
005935    삼성전자우  15849762   20011325   4161563  1207133611400  1528694164400   
051910     LG화학    709872     921975    212103   700823533000   908593419000   
096770  SK이노베이션   4848359    5515777    667418  1298854139000  1478890602000   

              순매수거래대금  
티커                     
005930  2054064769700  
000270   516414948600  
005935   321560553000  
051910   207769886000  
096770   180036463000  


# 2.1.1.12 종목별 시가 총액 조회
get_market_cap_by_ticker 함수는 특정 일자의 종목별 시가총액/거래량/거래대금/상장주식수/외국인보유주식수를 조회합니다. 시가총액과 거래대금의 단위는 원입니다. 외국인보유주식수는 D-2 (영업일 기준)일 까지 유효한 값이 출력되며, D-1일은 0으로 표기됩니다.

In [57]:
df = stock.get_market_cap_by_ticker("20210325")
print(df.head())

            종가             시가총액       거래량           거래대금       상장주식수
티커                                                                  
005930   81200  484746343060000  14758826  1200699288823  5969782550
000660  133000   96824314545000   4157799   550754976000   728002365
035420  380000   62420090100000    672585   255541387000   164263395
005935   73400   60399883780000    896035    65670738800   822886700
051910  788000   55626766284000    530883   421542798500    70592343


# 2.1.1.13 일자별 시가 총액 조회
get_market_cap_by_date 함수는 특정 종목의 일자별 시가총액을 조회합니다. 거래량/거래대금/상장주식수가 함께 조회됩니다.

In [58]:
df = stock.get_market_cap_by_date("20190101", "20190131", "005930")
print(df.head())

                       시가총액       거래량          거래대금       상장주식수
날짜                                                             
2019-01-02  231329073812500   7847664  304682623050  5969782550
2019-01-03  224463823880000  12471493  472966535350  5969782550
2019-01-04  223568356497500  14108958  525403005097  5969782550
2019-01-07  231329073812500  12748997  490833164150  5969782550
2019-01-08  227448715155000  12756554  491578269750  5969782550


get_market_cap_by_date() 함수에 frequency 파라미터(d/m/y)를 추가할 수 있습니다. d는 일자, m은 월, y는 연도를 의미합니다.

In [59]:
df = stock.get_market_cap_by_date("20200101", "20200430", "005930", "m")
print(df.head())

                       시가총액        거래량            거래대금       상장주식수
날짜                                                                
2020-01-31  336695735820000  319891636  18809460519447  5969782550
2020-02-29  323562214210000  360007160  21055346438502  5969782550
2020-03-31  285057116762500  856741868  42269216023680  5969782550
2020-04-30  298489127500000  424101937  20785194256247  5969782550


 20200101부터 20200430까지의 월별 시가총액을 조회합니다. 시가총액과 상장주식수는 월별 마지막 거래일의 값을 사용하며, 거래량과 거래대금은 합산된 결과가 출력됩니다. 조회 기간이 길 수록 데이터를 획득하기 까지의 시간이 오래 걸립니다.

# 2.1.1.14 티커별 외국인 보유량 및 외국인 한도소진률
get_exhaustion_rates_of_foreign_investment_by_ticker 함수는 상장주식수/외국인한도수량/외국인보유수량/외국인한도소진률 정보를 조회합니다. 외국인 보유수량 및 한도소진율은 장개시 시점 기준(금융감독원 외국인투자 관리시스템 제공 전일자 확정치)입니다.

In [60]:
df = stock.get_exhaustion_rates_of_foreign_investment_by_ticker('20200703')
print(df.head())

            상장주식수      보유수량        지분율       한도수량      한도소진율
티커                                                          
000020   27931470   1400966   5.019531   27931470   5.019531
000040   91661018  43190959  47.125000   91661018  47.125000
000050   27415270    773627   2.820312   27415270   2.820312
000060  113680000  12968255  11.406250  113680000  11.406250
000070    8564271    661240   7.718750    8564271   7.718750


두 번째 파라미터 market은 코스피(KOSPI)/코스닥(KOSDAQ)/코넥스(KONEX) 시장을 지정해서 조회할 수 있습니다.
세 번째 파라미터 balance_limit을 True로 지정하면 외국인 보유한도의 제한 종목만 검색할 수 있습니다. 지정하지 않으면 False 입니다.

In [61]:
df = stock.get_exhaustion_rates_of_foreign_investment_by_ticker('20200703', "KOSPI",
balance_limit=True)
print(df.head())

            상장주식수       보유수량        지분율       한도수량      한도소진율
티커                                                           
003490   94844634   12350096  13.023438   47412833  26.046875
003495    1110794      29061   2.619141     555286   5.230469
015760  641964077  127919592  19.937500  256785631  49.812500
017670   80745711   28962369  35.875000   39565398  73.187500
020560  223235294   13871465   6.210938  111595323  12.429688


# 2.1.1.15 일자별 외국인 보유량 및 외국인 한도소진률
get_exhaustion_rates_of_foreign_investment_by_date 함수는 특정한 종목의 일자별로 정렬된 상장주식수/외국인한도수량/외국인보유수량/외국인한도소진률 정보를 조회합니다. 외국인 보유수량 및 한도소진율은 장개시 시점 기준(금융감독원 외국인투자 관리시스템 제공 전일자 확정치)입니다.

In [63]:
df = stock.get_exhaustion_rates_of_foreign_investment_by_date("20210108", "20210115", "005930")
print(df.head())

            상장주식수       보유수량        지분율       한도수량      한도소진율
티커                                                           
003490  174209713   21410146  12.289062   87087436  24.578125
003495    1110794      21935   1.969727     555286   3.949219
015760  641964077  110185794  17.156250  256785631  42.906250
017670   80745711   27700645  34.312500   39565398  70.000000
020560  223235294   11589368   5.191406  111595323  10.390625


# 2.1.2 인덱스 조회 API
코스피 인덱스를 조회

# 2.1.2.1 인덱스 종류 조회
get_index_ticker_list() 함수는 코스피 인덱스를 리스트로 반환합니다.

In [64]:
tickers = stock.get_index_ticker_list()
print(tickers)

['1001', '1002', '1003', '1004', '1005', '1006', '1007', '1008', '1009', '1010', '1011', '1012', '1013', '1014', '1015', '1016', '1017', '1018', '1019', '1020', '1021', '1022', '1024', '1025', '1026', '1027', '1028', '1034', '1035', '1150', '1151', '1152', '1153', '1154', '1155', '1156', '1157', '1158', '1159', '1160', '1167', '1182', '1224', '1227', '1232', '1244']


현재의 인덱스와 과거의 인덱스가 다를 수 있기 때문에 일자를 입력하면 입력한 일자에 존재하는 인덱스를 반환 합니다.

In [65]:
tickers = stock.get_index_ticker_list("19800104")

코스닥 인덱스를 조회할 때는 market 옵션을 추가합니다

In [66]:
tickers = stock.get_index_ticker_list(market='KOSDAQ')

get_index_name 함수를 사용해서 티커의 이름을 얻을 수 있습니다.

In [67]:
for ticker in stock.get_index_ticker_list():
    print(ticker, stock.get_index_ticker_name(ticker))

1001 코스피
1002 코스피 대형주
1003 코스피 중형주
1004 코스피 소형주
1005 음식료품
1006 섬유의복
1007 종이목재
1008 화학
1009 의약품
1010 비금속광물
1011 철강금속
1012 기계
1013 전기전자
1014 의료정밀
1015 운수장비
1016 유통업
1017 전기가스업
1018 건설업
1019 운수창고업
1020 통신업
1021 금융업
1022 은행
1024 증권
1025 보험
1026 서비스업
1027 제조업
1028 코스피 200
1034 코스피 100
1035 코스피 50
1150 코스피 200 커뮤니케이션서비스
1151 코스피 200 건설
1152 코스피 200 중공업
1153 코스피 200 철강/소재
1154 코스피 200 에너지/화학
1155 코스피 200 정보기술
1156 코스피 200 금융
1157 코스피 200 생활소비재
1158 코스피 200 경기소비재
1159 코스피 200 산업재
1160 코스피 200 헬스케어
1167 코스피 200 중소형주
1182 코스피 200 초대형제외 지수
1224 코스피 200 비중상한 30%
1227 코스피 200 비중상한 25%
1232 코스피 200 비중상한 20%
1244 코스피200제외 코스피지수


# 2.1.2.3 인덱스 구성종목 조회
인덱스를 구성하고 있는 종목의 티커를 리스트로 반환합니다. 1005는 섬유의복 인덱스로, 이는 37개의 종목으로 구성돼 있음을 알 수 있습니다.

In [68]:
pdf = stock.get_index_portfolio_deposit_file("1005")
print(len(pdf), pdf)

37 ['097950', '271560', '000080', '007310', '004370', '005300', '001680', '280360', '049770', '017810', '003230', '005610', '005180', '145990', '002270', '136490', '001790', '036580', '101530', '001130', '003920', '248170', '033920', '000890', '008040', '264900', '011150', '003960', '027740', '004410', '006980', '014710', '002140', '006090', '002600', '023150', '003680']


# 2.1.2.3 인덱스 OHLCV 조회
get_index_ohlcv_by_date() 함수는 입력된 기간 동안의 인덱스 OHLCV를 조회합니다. 다음은 20190101-20190228 동안의 "코스피 200" 인덱스의 OHLCV를 조회합니다.

In [69]:
df = stock.get_index_ohlcv_by_date("20190101", "20190228", "1028")
print(df.head(2))

                시가      고가      저가      종가       거래량           거래대금
날짜                                                                 
2019-01-02  263.35  263.77  257.47  258.23  69949709  3186640984476
2019-01-03  258.19  258.70  255.35  255.77  90520685  3971916869836


get_index_ohlcv_by_date() 함수에 frequency 파라미터(d/m/y)를 추가할 수 있습니다. d는 일자, m은 월, y는 연도를 의미합니다. 다음은 20190101부터 20190228까지의 "코스피 200"의 월별 OHLCV를 출력합니다.

In [70]:
df = stock.get_index_ohlcv_by_date("20190101", "20190228", "1028", "m")
print(df.head(2))

                시가      고가      저가      종가         거래량
날짜                                                    
2019-01-31  263.35  288.87  254.55  285.89  2157758652
2019-02-28  287.07  290.32  280.02  283.80  1498968442


# 2.1.2.4 인덱스 상장 정보 조회
get_index_listing_date() 함수는 인덱스의 상장일 및 기준비수 정보를 조회합니다.
파라미터에는 KRX/KOSPI/KOSDAQ/테마를 입력할 수 있습니다.

In [71]:
df = stock.get_index_listing_date("KOSPI")
print(df.head())

                    기준시점        발표시점    기준지수  종목수
지수명                                              
코스피           1980.01.04  1983.01.04   100.0  799
코스피 200       1990.01.03  1994.06.15   100.0  201
코스피 100       2000.01.04  2000.03.02  1000.0  100
코스피 50        2000.01.04  2000.03.02  1000.0   50
코스피 200 중소형주  2010.01.04  2015.07.13  1000.0  101


# 2.1.2.5 인덱스 등락률 조회
get_index_price_change_by_ticker() 함수는 지수의 등락률/거래량/거래대금을 반환하며, KRX / KOSPI / KOSDAQ 세 개의 지수를 지원합니다. 코스피, 코스닥 지수의 통계(거래량, 거래대금 등)는 외국주 등까지 포함한 시장 전체 통계입니다.



In [72]:
df = stock.get_index_price_change_by_ticker("20200520", "20200527", "KOSDAQ")
print(df.head())

                        시가       종가       등락률          거래량            거래대금
지수명                                                                       
코스닥                 696.36   724.59  4.050781  10488319776  62986196230829
코스닥 150            1065.42  1102.57  3.490234    729479528  18619100922088
코스닥 150 정보기술        603.58   631.64  4.648438    268338653   5203201290465
코스닥 150 헬스케어       3450.56  3532.41  2.369141    135927364   7874689575610
코스닥 150 커뮤니케이션서비스  2037.30  2090.19  2.599609     25001250    816778277690


# 2.1.3 공매도 API
KRX는 (T+2)일 이후의 데이터를 제공합니다. 최근 영업일이 20190405라면 20190403일을 포함한 이전 데이터를 얻을 수 있습니다.

# 2.1.3.1 종목별 공매도 현황
get_shorting_status_by_date() 메서드는 시작일/종료일/티커 세 개의 파라미터를 입력받아 공매도 현황을 DataFrame으로 반환합니다.

In [73]:
df = stock.get_shorting_status_by_date("20181210", "20181212", "005930")
print(df)

                거래량     잔고수량         거래대금          잔고금액
날짜                                                     
2018-12-10  2180611  4728327  87700923850  190078745400
2018-12-11   701924  4249549  28291624600  171044347250
2018-12-12    40002  4236519   1618884450  171367193550


당일 잔고와 (전일 잔고 + 당일 공매도 - 당일 상환) 수량은 정확하게 일치하지 않을 수 있습니다. 이는 투자자가 보유한 공매도잔고 비율이 상장주식수의 0.01% 미만인 경우 보고의 의무가 없기 때문에 집계되지 않을 수 있습니다.

# 2.1.3.2 종목별 공매도 거래 정보
get_shorting_volume_by_ticker 함수는 입력받은 일자의 공매도 거래량 정보를 반환합니다.

In [74]:
df = stock.get_shorting_volume_by_ticker("20210125")
print(df.head(3))

          공매도       매수    비중
티커                          
095570     32   180458  0.02
006840     79   386257  0.02
027410  18502  8453962  0.22


코스피(KOSPI)/코스닥(KOSDAQ)/코넥스(KONEX)의 공매도 거래량을 조회할 수 있습니다. 사용하지 않을 경우 코스피가 선택됩니다.

In [75]:
df = stock.get_shorting_volume_by_ticker("20210125", "KOSDAQ")
print(df.head())

        공매도       매수    비중
티커                        
060310    0   328833  0.00
054620    0   106187  0.00
265520    0   285869  0.00
211270    0  1373332  0.00
035760   18   291125  0.01


조회하려는 증권의 세부 종류를 리스트로 지정할 수 있습니다. 리스트에 사용될 수 있는 상세 구분항목은 다음과 같습니다.

주식, ETF, ETN, ELW, 신주인수권증서및증권, 수익증권

In [77]:
df = stock.get_shorting_volume_by_ticker("20210125", include=["주식", "ELW"])
print(df.head())

          공매도       매수    비중
티커                          
095570     32   180458  0.02
006840     79   386257  0.02
027410  18502  8453962  0.22
282330     96    82986  0.12
138930   1889  1181748  0.16


get_shorting_value_by_ticker 함수는 입력받은 일자의 공매도 거래대금 정보를 반환합니다. 사용 방법은 get_shorting_volume_by_ticker 함수와 동일합니다.

# 2.1.3.3 일자별 공매도 거래 현황
get_shorting_volume_by_date() 함수는 입력받은 종목에 대해 주어진 기간 동안의 공매도 거래 정보를 반환합니다.

In [78]:
df = df = stock.get_shorting_volume_by_date("20210104", "20210108", "005930")
print(df.head(3))

             공매도        매수    비중
날짜                              
2021-01-04  9279  38655276  0.02
2021-01-05   169  35335669  0.00
2021-01-06   967  42089013  0.00


# 2.1.3.4 투자자별 공매도 거래 현황 (거래량)
get_shorting_investor_volume_by_date 함수는 시작일/종료일 두 개의 파라미터를 입력받아 해당 기간동안 코스피 종목의 투자자별 공매도 거래량을 DataFrame으로 반환합니다.

In [80]:
df = stock.get_shorting_investor_volume_by_date("20190401", "20190405", "KOSPI")
print(df.head())

                 기관      개인      외국인    기타        합계
날짜                                                  
2019-04-01  3402249  133996  5702788   200   9239233
2019-04-02  2883434  139801  5580395     0   8603630
2019-04-03  3589910  127075  6375248     0  10092233
2019-04-04  3200221  119193  5604505  1405   8925324
2019-04-05  3163018  134396  6882981  1754  10182149


market 옵션을 사용하면 코스닥의 공매도 거래량을 조회할 수 있습니다. 사용하지 않을 경우 코스피가 선택됩니다.

In [81]:
df = stock.get_shorting_investor_volume_by_date("20190401", "20190405", "KOSDAQ")
print(df.head())

                 기관      개인      외국인   기타       합계
날짜                                                
2019-04-01   913528  398779  5283672    0  6595979
2019-04-02   841544  267618  7295980  249  8405391
2019-04-03   874047  208539  6526794    0  7609380
2019-04-04  1136765  192503  6566776    0  7896044
2019-04-05  1051807  232488  6618597    0  7902892


# 2.1.3.5 투자자별 공매도 거래 현황 (거래대금)
get_shorting_investor_value_by_date 함수는 시작일/종료일 두 개의 파라미터를 입력받아 해당 기간동안 코스피 종목의 투자자별 공매도 거래대금을 DataFrame으로 반환합니다.

In [82]:
df = stock.get_shorting_investor_value_by_date("20190401", "20190405", "KOSPI")
print(df.head())

                      기관          개인           외국인        기타            합계
날짜                                                                        
2019-04-01  105536073368  2936388505  168285844893  30302100  276788608866
2019-04-02   96384728941  2951117600  160734480125         0  260070326666
2019-04-03  112539971387  2169492030  180355524574         0  295064987991
2019-04-04   92635400253  2294543280  175873863029  10918080  270814724642
2019-04-05   90581343837  1221266912  150558110496   2218810  242362940055


코스닥의 공매도 거래량 또한 조회할 수 있습니다.

In [83]:
df = stock.get_shorting_investor_value_by_date("20190401", "20190405", "KOSDAQ")
print(df.head())

                     기관          개인          외국인       기타           합계
날짜                                                                    
2019-04-01  20345961749  2766677625  69741628204        0  92854267578
2019-04-02  18131296688  1614215195  65974380594  7009350  85726901827
2019-04-03  12288386154  2796139160  83568208742        0  98652734056
2019-04-04  23535031919  2293798208  70410033688        0  96238863815
2019-04-05  26473311289  2117625828  70100665837        0  98691602954


# 2.1.3.6 종목별 공매도 잔고 현황
get_shorting_balance_by_date 메서드는 시작일/종료일 두 개의 파라미터를 입력받아 해당 기간동안 공매도 잔고 정보를 DataFrame으로 반환합니다.

In [84]:
df = stock.get_shorting_balance_by_date("20190401", "20190405", "005930")
print(df.head())

              공매도잔고       상장주식수         공매도금액          시가총액    비중
날짜                                                               
2019-04-01  3403293  5969782550  153318349650  2.689387e+14  0.06
2019-04-02  3435390  5969782550  157169092500  2.731176e+14  0.06
2019-04-03  3380137  5969782550  157514384200  2.781919e+14  0.06
2019-04-04  3419184  5969782550  160530688800  2.802813e+14  0.06
2019-04-05  3421622  5969782550  160302990700  2.796843e+14  0.06


# 2.1.3.7 공매도 거래비중 상위 50 종목
get_shorting_trade_top50 메서드는 조회일자를 입력받아 해당일 코스피 종목의 거래 비중 TOP 50을 DataFrame으로 반환합니다. 거래 비중은 거래대금/거래대금로 계산합니다.

In [85]:
df = stock.get_shorting_volume_top50("20210129")
print(df.head())

        순위   공매도거래대금      총거래대금  공매도비중  직전40일거래대금평균  공매도거래대금증가율  직전40일공매도평균비중  \
티커                                                                              
003545   1  38510030  915824030   4.21      5814411        6.62          0.51   
267290   2  13265200  329805000   4.02      2755259        4.82          0.66   
015890   3  15865860  428852660   3.70      8316412        1.91          1.30   
005945   4  25401240  908915950   2.79      4610634        5.51          0.44   
227840   5  13784400  546597900   2.52      3084294        4.47          0.51   

        공매도비중증가율  주가수익률  
티커                       
003545      8.33  -1.25  
267290      6.14  -2.46  
015890      2.85  -4.46  
005945      6.40  -0.35  
227840      4.91  -2.37  


# 2.1.3.8 종목별 공매도 잔고 TOP 50
get_shorting_balance_top50 메서드는 조회 일자를 입력받아 공매도 비중이 높은 상위 50개 종목 정보를 반환합니다. 공매비중은 공매도 잔고/상장주식수로 계산합니다.

In [86]:
df = stock.get_shorting_balance_top50("20210127")
print(df.head())

        순위     공매도잔고      상장주식수          공매도금액          시가총액        비중
티커                                                                    
032350   1   4693027   69275662    74853780650  1.104947e+12  6.769531
042670   2  10846251  215931625    92843908560  1.848375e+12  5.019531
068270   3   6523965  134997805  2146384485000  4.441428e+13  4.828125
008770   4   1269261   39248121   106237145700  3.285068e+12  3.230469
011690   5   1604890   58494201     1957965800  7.136293e+10  2.740234


코스닥 또한 거래량을 조회할 수 있습니다.

In [88]:
df = stock.get_shorting_balance_top50("20210129", market="KOSDAQ")
print(df.head())

        순위    공매도잔고      상장주식수         공매도금액          시가총액        비중
티커                                                                  
215600   1  6497785   71617125   78623198500  8.665672e+11  9.070312
028300   2  3296305   53013031  296667450000  4.771173e+12  6.218750
032500   3  2259284   39820883  173964868000  3.066208e+12  5.671875
078130   4  4039187  126348384   17065565075  5.338219e+11  3.199219
084990   5   912821   34265714   23413858650  8.789156e+11  2.660156


# 2.2 ETX API
# 2.2.1 ETF
# 2.2.1.1 ETF 티커
get_etf_ticker_list 함수는 입력된 날짜에 존재하는 ETF 티커를 리스트로 반환합니다.

In [89]:
tickers = stock.get_etf_ticker_list("20200717")
print(tickers[:10])

['292340', '159800', '285000', '287300', '287310', '290080', '284980', '287320', '287330', '252400']


20021014에는 KODEX 200(069500)과 KOSEF 200(069660) 두 개의 종목이 상장돼 있었습니다.

In [91]:
tickers = stock.get_etf_ticker_list("20021014")
print(tickers)

['069500', '069660']


# 2.2.1.1 ETF 이름
get_etf_ticker_name 함수는 입력된 티커의 종목 이름을 출력합니다.

In [99]:
tickers = stock.get_etf_ticker_list("20021014")
print(stock.get_etf_ticker_name(tickers))

ticker
069500    KODEX 200
069660    KOSEF 200
Name: 종목명, dtype: object


# 2.2.1.1 ETF OHLCV
get_etf_ohlcv_by_date 함수는 ETF의 OHLCV를 일자별로 출력합니다. 다음은 "마이티 200커버드콜ATM레버리지(292340)"의 OHLCV를 출력합니다.

In [100]:
df = stock.get_etf_ohlcv_by_date("20210104", "20210108", "292340")
print(df.head())

                NAV    시가    고가    저가    종가  거래량    거래대금     기초지수
날짜                                                               
2021-01-04  9737.23  9730  9730  9730  9730   81  788130  1303.29
2021-01-05  9756.27  9705  9990  9700  9770    6   58845  1306.59
2021-01-06  9796.98     0     0     0  9770    0       0  1306.76
2021-01-07  9723.65  9845  9855  9845  9855    2   19700  1301.65
2021-01-08  9771.73  9895  9900  9855  9885    6   59320  1306.73


get_etf_ohlcv_by_date() 함수에 frequency 파라미터(d/m/y)를 추가할 수 있습니다. d는 일자, m은 월, y는 연도를 의미합니다. 다음은 20200101부터 20200531까지의 월별 OHLCV를 출력합니다.

In [101]:
df = stock.get_etf_ohlcv_by_date("20200101", "20200531", "292340", 'm')
print(df.head())

                NAV    시가    고가  저가    종가     거래량        거래대금     기초지수
날짜                                                                    
2020-01-31  8910.61  8900  9270   0  8795   36559   330991070  1231.00
2020-02-29  8633.13     0  9395   0  7555      72      658080  1213.88
2020-03-31  7720.09  7520  9965   0  6030  206070  1373727350  1149.86
2020-04-30  5590.35  6055  6975   0  6975    8743    57352845   997.80
2020-05-31  6845.59  6835  7450   0  7415    1788    13057270  1107.92


# 2.2.1.2 전종목의 OHLCV 조회
get_etf_ohlcv_by_ticker 함수는 입력된 일자의 전종목의 OHLCV를 출력합니다.

In [102]:
df = stock.get_etf_ohlcv_by_ticker("20210325")
print(df.head())

             NAV     시가     고가     저가     종가    거래량        거래대금     기초지수
티커                                                                      
152100  41887.33  41705  42145  41585  41835  59317  2479398465   408.53
295820  10969.41  10780  10945  10780  10915     69      750210  2364.03
253150  46182.13  45640  46700  45540  46145   1561    71730335  2043.75
253160   4344.07   4400   4400   4295   4340  58943   256679440  2043.75
278420   9145.45   9055   9150   9055   9105   1164    10598375  1234.03


휴일을 조회하면 비어있는 DataFrame이 반환됩니다.

In [103]:
df = stock.get_etf_ohlcv_by_ticker("20210321")
print(df.head())

Empty DataFrame
Columns: []
Index: []


# 2.2.1.3 전종목의 등락률 조회
get_etf_price_change_by_ticker 함수는 특정 기간 동안의 전종목 등락률을 반환합니다.

In [105]:
df = stock.get_etf_price_change_by_ticker("20210325", "20210402")
print(df.head())

           시가     종가   변동폭   등락률      거래량         거래대금
티커                                                    
152100  41715  43405  1690  4.05  1002296  42802174550
295820  10855  11185   330  3.04     1244     13820930
253150  45770  49735  3965  8.66    13603    650641700
253160   4380   4015  -365 -8.33   488304   2040509925
278420   9095   9385   290  3.19     9114     84463155


# 2.2.1.4 PDF 정보
get_etf_portfolio_deposit_file 함수는 ETF를 구성하는 종목/비중 정보를 얻어옵니다. 다음은 ARIRANG 200(152100)의 PDF를 조회합니다.

In [106]:
df = stock.get_etf_portfolio_deposit_file("152100")
print(df.head())

           계약수         금액     비중
티커                              
005930  8140.0  680504000  31.18
000660   968.0  135520000   6.08
035420   218.0   83603000   3.85
051910    79.0   64148000   2.97
006400    89.0   59007000   2.68


날짜를 입력해서 특정일의 상태를 확인할 수 있습니다.

In [107]:
df = stock.get_etf_portfolio_deposit_file("152100", "20161206")
print(df.head())

           계약수         금액     비중
티커                              
005930   190.0  326420000  25.85
000660  1059.0   47019600   3.73
005380   279.0   37386000   2.96
035420    47.0   35908000   2.77
005490   134.0   33433000   2.70


# 2.2.1.5 괴리율 추이
get_etf_price_deviation 함수는 ETF의 종가/순자산가치/괴리율 정보를 얻어옵니다. 다음은 ARIRANG 200동일가중(295820) 종목의 괴리율을 출력합니다.

In [108]:
df = stock.get_etf_price_deviation("20200101", "20200401", "295820")
print(df.head())

              종가      NAV   괴리율
날짜                             
2020-01-02  8285  8302.58 -0.21
2020-01-03  8290  8297.89 -0.10
2020-01-06  8150  8145.95  0.05
2020-01-07  8220  8226.05 -0.07
2020-01-08  7980  7998.84 -0.24


2.2.1.6 추적오차율 추이
get_etf_tracking_error 함수는 ETF의 순자산가치/기초지수/추적오차 정보를 얻어옵니다.

In [110]:
df = stock.get_etf_tracking_error("20210104", "20210108", "295820")
print(df.head())

                 NAV       지수  추적오차율
날짜                                  
2021-01-04  10267.39  2218.76   0.82
2021-01-05  10459.99  2261.10   0.81
2021-01-06  10431.90  2254.82   0.81
2021-01-07  10648.76  2302.73   0.82
2021-01-08  10797.72  2335.10   0.82


# 2.2.2 ETN
# 2.2.2.1 ETN 티커
get_etn_ticker_list 함수는 입력된 날짜에 존재하는 ETN 티커를 리스트로 반환합니다.

In [111]:
tickers = stock.get_etn_ticker_list("20141215")
print(tickers)

['500001', '500002']


# 2.2.2.1 ETF 이름
get_etn_ticker_name 함수는 입력된 티커의 종목 이름을 출력합니다.

In [113]:
tickers = stock.get_etn_ticker_list("20141215")
print(stock.get_etn_ticker_name(tickers))

ticker
500001    신한 K200 USD 선물 바이셀 ETN
500002    신한 USD K200 선물 바이셀 ETN
Name: 종목명, dtype: object


# 2.2.3 ELW
# 2.2.3.1 ELW 티커
get_elw_ticker_list 함수는 입력된 날짜에 존재하는 ELW 티커를 리스트로 반환합니다.

In [120]:
tickers = stock.get_elw_ticker_list("20200810")
print(tickers)

['58F937', '57FF87']


# 2.2.3.1 ELW 이름
get_etn_ticker_name 함수는 입력된 티커의 종목 이름을 출력합니다.

In [123]:
tickers = stock.get_elw_ticker_list("20200810")
print(stock.get_elw_ticker_name(tickers))

ticker
58F937    KBF937삼성전자콜
57FF87    한국FF87삼성전자콜
Name: 종목명, dtype: object
